import React from "react";

const wordsEnglish = [
    [
        { id: 1, english: "refuse", polish: "odrzucać", correct:null},
        { id: 2, english: "threaten", polish: "grozić", correct:null},
        { id: 3, english: "convince", polish: "przekonać", correct:null},
        { id: 4, english: "encourage", polish: "zachęcać", correct:null},
        { id: 5, english: "persuade", polish: "namawiać", correct:null},
        { id: 6, english: "warn", polish: "ostrzec", correct:null},
        { id: 7, english: "accuse sb of ", polish: "oskarżać kogoś o", correct:null},
        { id: 8, english: "admit", polish: "przyznać", correct:null},
        { id: 9, english: "blame sb for ", polish: "winić kogoś o", correct:null},
        { id: 10, english: "deny", polish: "zaprzeczać", correct:null},
    ],
    [
        { id: 11, english: "insist on", polish: "nalegać", correct:null},
        { id: 12, english: "regret", polish: "żałować", correct:null},
        { id: 13, english: "advertise", polish: "reklamować", correct:null},
        { id: 14, english: "advertisement", polish: "reklama", correct:null},
        { id: 15, english: "complain", polish: "narzekać", correct:null},
        { id: 16, english: "complaint", polish: "skarga", correct:null},
        { id: 17, english: "involving ", polish: "wymagający", correct:null},
        { id: 18, english: "achievable", polish: "osiągalny", correct:null},
        { id: 19, english: "unforeseen ", polish: "nieprzewidywalny", correct:null},
        { id: 20, english: "achievement", polish: "osiągnięcie", correct:null},
    ],
    [
        { id: 21, english: "achieve", polish: "osiągać", correct:null},
        { id: 22, english: "awareness", polish: "świadomość", correct:null},
        { id: 23, english: "aware", polish: "świadomy", correct:null},
        { id: 24, english: "fossil fuels", polish: "paliwo kopalne", correct:null},
        { id: 25, english: "involve", polish: "wymagać", correct:null},
        { id: 26, english: "involvement", polish: "udział", correct:null},
        { id: 27, english: "appear ", polish: "wyglądać", correct:null},
        { id: 28, english: "appearance", polish: "wygląd", correct:null},
        { id: 29, english: "distance ", polish: "odległość", correct:null},
        { id: 30, english: "distant", polish: "odległy", correct:null},
    ],
    [
        { id: 31, english: "contribute", polish: "wynosić", correct:null},
        { id: 32, english: "in addition", polish: "dodatkowo", correct:null},
        { id: 33, english: "contribution", polish: "wkład", correct:null},
        { id: 34, english: "majority", polish: "większość", correct:null},
        { id: 35, english: "unable", polish: "niezdolny", correct:null},
        { id: 36, english: "addict", polish: "nałogowiec", correct:null},
        { id: 37, english: "addiction ", polish: "uzależnienie", correct:null},
        { id: 38, english: "persuading", polish: "przekonywanie", correct:null},
        { id: 39, english: "fed up", polish: "mieć dość", correct:null},
        { id: 40, english: "obey", polish: "przestrzegać", correct:null},
    ],
    [
        { id: 41, english: "rightly or wrongly", polish: "słusznie czy niesłusznie", correct:null},
        { id: 42, english: "sooner or later", polish: "prędzej czy później", correct:null},
        { id: 43, english: "all or nothing", polish: "wszystko albo nic", correct:null},
        { id: 44, english: "more or less", polish: "więcej lub mniej", correct:null},
        { id: 45, english: "distracting", polish: "rozpraszający", correct:null},
        { id: 46, english: "distract", polish: "rozpraszać", correct:null},
        { id: 47, english: "disturb ", polish: "przeszkadzać", correct:null},
        { id: 48, english: "properly", polish: "prawidłowo", correct:null},
        { id: 49, english: "beforehand ", polish: "przedtem", correct:null},
        { id: 50, english: "support", polish: "wspierać", correct:null},

    ],
    [
        { id: 51, english: "withhold", polish: "zatrzymać coś dla siebie", correct:null},
        { id: 52, english: "burden", polish: "ciężar", correct:null},
        { id: 53, english: "duty", polish: "obowiązek", correct:null},
        { id: 54, english: "come down", polish: "opaść", correct:null},
        { id: 55, english: "modest", polish: "skromny", correct:null},
        { id: 56, english: "inaudible", polish: "niesłyszalny", correct:null},
        { id: 57, english: "relieve", polish: "ulżyć", correct:null},
        { id: 58, english: "momentous", polish: "wyniosły", correct:null},
        { id: 59, english: "mankind ", polish: "ludzkość", correct:null},
        { id: 60, english: "meaningful", polish: "znaczący", correct:null},

    ],
    [
        { id: 61, english: "memorable", polish: "pamiętny", correct:null},
        { id: 62, english: "dawn", polish: "świt", correct:null},
        { id: 63, english: "claim", polish: "twierdzić", correct:null},
        { id: 64, english: "amazingly", polish: "zdumiewająco", correct:null},
        { id: 65, english: "despite", polish: "mimo", correct:null},
        { id: 66, english: "fertilizer", polish: "nawóz", correct:null},
        { id: 67, english: "decline ", polish: "ubytek", correct:null},
        { id: 68, english: "except", polish: "oprócz", correct:null},
        { id: 69, english: "prevent", polish: "zapobiegać", correct:null},
        { id: 70, english: "relatives", polish: "krewni", correct:null},

    ],
    [
        { id: 71, english: "funeral", polish: "pogrzeb", correct:null},
        { id: 72, english: "injections", polish: "zastrzyki", correct:null},
        { id: 73, english: "because of", polish: "z powodu", correct:null},
        { id: 74, english: "according to", polish: "według", correct:null},
        { id: 75, english: "so that", polish: "tak, żeby", correct:null},
        { id: 76, english: "downside", polish: "negatywna strona", correct:null},
        { id: 77, english: "apparently ", polish: "najwyraźniej", correct:null},
        { id: 78, english: "gradually", polish: "stopniowo", correct:null},
        { id: 79, english: "obviously ", polish: "oczywiście", correct:null},
        { id: 80, english: "harmful", polish: "krzywdzący", correct:null},

    ],
    [
        { id: 81, english: "to complain about", polish: "narzekać na", correct:null},
        { id: 82, english: "worth saying", polish: "warte powiedzenia", correct:null},
        { id: 83, english: "notice", polish: "zauważać", correct:null},
        { id: 84, english: "be noticed", polish: "być zauważonym", correct:null},
        { id: 85, english: "permission", polish: "pozwolenie", correct:null},
        { id: 86, english: "opportunity", polish: "możliwość", correct:null},
        { id: 87, english: "unpredictability", polish: "nieprzewidywalność", correct:null},
        { id: 88, english: "drop", polish: "upaść", correct:null},
        { id: 89, english: "frightening", polish: "przerażający", correct:null},
        { id: 90, english: "performance", polish: "występ", correct:null},
    ],
    [{ id: 91, english: "impact", polish: "wpływ", correct:null},
        { id: 92, english: "ways to make a living", polish: "sposoby zarabiania na życie", correct:null},
        { id: 93, english: "biased", polish: "stronniczy", correct:null},
        { id: 94, english: "accurate", polish: "poprawny", correct:null},
        { id: 95, english: "censored", polish: "ocenzurowany", correct:null},
        { id: 96, english: "striped", polish: "w paski", correct:null},
        { id: 97, english: "checked ", polish: "w kratkę", correct:null},
        { id: 98, english: "patterned", polish: "wzorzyste", correct:null},
        { id: 99, english: "blister ", polish: "odcisk", correct:null},
        { id: 100, english: "unconscious", polish: "nieprzytomny", correct:null},
    ]
];

export {wordsEnglish};